sudo: required
dist: trusty

os: linux

language: c

cache:
  apt: true

addons:
  apt:
    packages:
    - axel
    - cpanminus
    - libtest-base-perl
    - libtext-diff-perl
    - liburi-perl
    - libwww-perl
    - libtest-longstring-perl
    - liblist-moreutils-perl

compiler:
  - gcc
  - clang

env:
  global:
    - LUAJIT_PREFIX=/opt/luajit21
    - LUAJIT_LIB=$LUAJIT_PREFIX/lib
    - LD_LIBRARY_PATH=$LUAJIT_LIB:$LD_LIBRARY_PATH
    - LUAJIT_INC=$LUAJIT_PREFIX/include/luajit-2.1
    - LUA_INCLUDE_DIR=$LUAJIT_INC
    - LUA_CMODULE_DIR=/lib
    - JOBS=3
    - NGX_BUILD_JOBS=$JOBS
  matrix:
    - NGINX_VERSION=1.9.15
      BUILD_SH=build.sh
      TEST_CASE=t
    - NGINX_VERSION=1.11.2
      BUILD_SH=build.sh
      TEST_CASE=t
    - NGINX_VERSION=1.9.15
      BUILD_SH=build-only-http.sh
      TEST_CASE=t/http-*
    - NGINX_VERSION=1.11.2
      BUILD_SH=build-only-http.sh
      TEST_CASE=t/http-*
    - NGINX_VERSION=1.9.15
      BUILD_SH=build-only-stream.sh
      TEST_CASE=t/stream-*
    - NGINX_VERSION=1.11.2
      BUILD_SH=build-only-stream.sh
      TEST_CASE=t/stream-*

install:
  - echo $HOME
  - git clone https://github.com/openresty/nginx-devel-utils.git
  - git clone https://github.com/openresty/openresty.git ../openresty
  - git clone https://github.com/openresty/no-pool-nginx.git ../no-pool-nginx
  - git clone https://github.com/simpl/ngx_devel_kit.git ../ndk-nginx-module
  - git clone -b without_ngx_http_lua_dependent https://github.com/rainingmaster/test-nginx.git
  - git clone -b v2.1-agentzh https://github.com/openresty/luajit2.git
  - git clone https://github.com/rainingmaster/socket-get-module.git ../socket-get-module
  - git clone https://github.com/openresty/lua-nginx-module.git ../http-lua-nginx-module
  - git clone -b shm_based https://github.com/rainingmaster/stream-lua-nginx-module.git ../stream-lua-nginx-module
  - git clone https://github.com/openresty/nginx-eval-module.git ../eval-nginx-module
  - git clone https://github.com/openresty/echo-nginx-module.git ../echo-nginx-module
  - git clone https://github.com/openresty/set-misc-nginx-module.git ../set-misc-nginx-module
  - git clone https://github.com/openresty/openresty.git ../ngx_openresty

script:
  - cd luajit2
  - make -j$JOBS CCDEBUG=-g Q= PREFIX=$LUAJIT_PREFIX CC=$CC XCFLAGS='-DLUA_USE_APICHECK -DLUA_USE_ASSERT' > build.log 2>&1 || (cat build.log && exit 1)
  - sudo make install PREFIX=$LUAJIT_PREFIX > build.log 2>&1 || (cat build.log && exit 1)
  - cd ..
  - cd test-nginx && sudo cpanm . && cd ..
  - export PATH=$PWD/work/nginx/sbin:$PWD/nginx-devel-utils:$PATH
  - export NGX_BUILD_CC=$CC
  - sh util/$BUILD_SH $NGINX_VERSION > build.log 2>&1 || (cat build.log && exit 1)
  - nginx -V
  - ldd `which nginx`|grep luajit
  - prove -r $TEST_CASE
